import TopBar from '@/components/TopBar';
import { FileText, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function TermsOfService() {
  return (
    <div className="flex flex-col h-screen overflow-hidden bg-background">
      <TopBar />
      <div className="flex-1 overflow-y-auto scrollbar-thin">
        <div className="max-w-2xl mx-auto p-4 sm:p-6 space-y-6 pb-12">
          <div className="flex items-center gap-3">
            <Link to="/" className="p-1.5 rounded-md hover:bg-accent text-muted-foreground transition-colors">
              <ArrowLeft className="w-4 h-4" />
            </Link>
            <FileText className="w-5 h-5 text-primary" />
            <h1 className="text-xl font-bold text-foreground">Terms of Service</h1>
          </div>
          <p className="text-xs text-muted-foreground">Last updated: March 20, 2026</p>

          <div className="bg-card rounded-lg border border-border p-5 sm:p-6 space-y-5 text-sm text-muted-foreground leading-relaxed">
            <Section title="1. Acceptance of Terms">
              <p>By accessing or using MarketLens, you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the application.</p>
            </Section>

            <Section title="2. Description of Service">
              <p>MarketLens is an <strong className="text-foreground">AI-powered market research and analysis tool</strong> that provides:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-xs">
                <li>AI-generated market insights and trend analysis</li>
                <li>Technical indicator visualizations</li>
                <li>Paper trading simulation with virtual currency</li>
                <li>Watchlist and portfolio tracking (simulation only)</li>
              </ul>
            </Section>

            <Section title="3. Not Financial Advice">
              <p className="font-semibold text-warning">MarketLens does NOT provide financial advice, investment recommendations, or solicitations to buy or sell any financial instrument.</p>
              <p className="mt-2">All outputs, predictions, insights, and analyses are for <strong className="text-foreground">informational and educational purposes only</strong>. They are generated by experimental AI models and may be inaccurate, incomplete, or outdated.</p>
              <p className="mt-2">You should always conduct your own research and consult a qualified financial advisor before making any investment decisions.</p>
            </Section>

            <Section title="4. Simulation Mode">
              <p>All trading features within MarketLens operate in <strong className="text-foreground">simulation mode only</strong>:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-xs">
                <li>No real money is involved in any transaction</li>
                <li>Virtual balances and portfolios have no monetary value</li>
                <li>Simulated results do not reflect actual market conditions including slippage, liquidity, fees, and execution delays</li>
                <li>Past simulated performance does not indicate future results</li>
              </ul>
            </Section>

            <Section title="5. AI Model Limitations">
              <p>AI-generated insights are <strong className="text-foreground">experimental model outputs</strong> that:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-xs">
                <li>Are probabilistic in nature and may be wrong</li>
                <li>May not account for all market factors, breaking news, or black swan events</li>
                <li>Should not be the sole basis for any financial decision</li>
                <li>May exhibit biases present in training data</li>
              </ul>
            </Section>

            <Section title="6. User Responsibilities">
              <ul className="list-disc list-inside space-y-1 text-xs">
                <li>You are solely responsible for any financial decisions you make</li>
                <li>You must not use this app as a substitute for professional financial advice</li>
                <li>You agree not to misrepresent AI outputs as certified financial recommendations</li>
                <li>You must be at least 18 years old to use this service</li>
              </ul>
            </Section>

            <Section title="7. Prohibited Uses">
              <p>You agree not to:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-xs">
                <li>Use the app for automated trading or connect it to any brokerage</li>
                <li>Redistribute AI-generated insights as professional financial advice</li>
                <li>Attempt to reverse-engineer or extract the AI models</li>
                <li>Use the service in violation of any applicable laws or regulations</li>
              </ul>
            </Section>

            <Section title="8. Limitation of Liability">
              <p>To the maximum extent permitted by law, MarketLens and its creators shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from:</p>
              <ul className="list-disc list-inside space-y-1 mt-2 text-xs">
                <li>Use of or reliance on AI-generated insights</li>
                <li>Financial losses from decisions influenced by the app</li>
                <li>Inaccurate, delayed, or missing market data</li>
                <li>Service interruptions or technical failures</li>
              </ul>
            </Section>

            <Section title="9. Disclaimer of Warranties">
              <p>The service is provided <strong className="text-foreground">"as is"</strong> and <strong className="text-foreground">"as available"</strong> without warranties of any kind, express or implied, including but not limited to warranties of accuracy, reliability, or fitness for a particular purpose.</p>
            </Section>

            <Section title="10. Modifications">
              <p>We reserve the right to modify these Terms at any time. Continued use of the app after changes constitutes acceptance of the updated terms.</p>
            </Section>

            <Section title="11. Termination">
              <p>We may suspend or terminate your access to MarketLens at any time, with or without cause, without prior notice.</p>
            </Section>

            <Section title="12. Governing Law">
              <p>These Terms shall be governed by and construed in accordance with applicable laws. Any disputes arising from these terms shall be resolved through appropriate legal channels.</p>
            </Section>

            <Section title="13. Contact">
              <p>For questions regarding these Terms, please reach out through the app's support channels.</p>
            </Section>
          </div>
        </div>
      </div>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h3 className="text-foreground font-semibold mb-2">{title}</h3>
      {children}
    </section>
  );
}
