INSERT INTO watchlist_stocks (symbol, name, yahoo_symbol, stock_type) VALUES
('ADANIENT', 'Adani Enterprises', 'ADANIENT.NS', 'stock'),
('ADANIPORTS', 'Adani Ports & SEZ', 'ADANIPORTS.NS', 'stock'),
('APOLLOHOSP', 'Apollo Hospitals', 'APOLLOHOSP.NS', 'stock'),
('ASIANPAINT', 'Asian Paints', 'ASIANPAINT.NS', 'stock'),
('AXISBANK', 'Axis Bank', 'AXISBANK.NS', 'stock'),
('BAJAJ-AUTO', 'Bajaj Auto', 'BAJAJ-AUTO.NS', 'stock'),
('BAJFINANCE', 'Bajaj Finance', 'BAJFINANCE.NS', 'stock'),
('BAJAJFINSV', 'Bajaj Finserv', 'BAJAJFINSV.NS', 'stock'),
('BEL', 'Bharat Electronics', 'BEL.NS', 'stock'),
('BPCL', 'Bharat Petroleum', 'BPCL.NS', 'stock'),
('BRITANNIA', 'Britannia Industries', 'BRITANNIA.NS', 'stock'),
('CIPLA', 'Cipla', 'CIPLA.NS', 'stock'),
('COALINDIA', 'Coal India', 'COALINDIA.NS', 'stock'),
('DIVISLAB', 'Divi''s Laboratories', 'DIVISLAB.NS', 'stock'),
('DRREDDY', 'Dr. Reddy''s', 'DRREDDY.NS', 'stock'),
('EICHERMOT', 'Eicher Motors', 'EICHERMOT.NS', 'stock'),
('GRASIM', 'Grasim Industries', 'GRASIM.NS', 'stock'),
('HCLTECH', 'HCL Technologies', 'HCLTECH.NS', 'stock'),
('HDFCLIFE', 'HDFC Life Insurance', 'HDFCLIFE.NS', 'stock'),
('HEROMOTOCO', 'Hero MotoCorp', 'HEROMOTOCO.NS', 'stock'),
('HINDALCO', 'Hindalco Industries', 'HINDALCO.NS', 'stock'),
('HINDUNILVR', 'Hindustan Unilever', 'HINDUNILVR.NS', 'stock'),
('INDUSINDBK', 'IndusInd Bank', 'INDUSINDBK.NS', 'stock'),
('JSWSTEEL', 'JSW Steel', 'JSWSTEEL.NS', 'stock'),
('KOTAKBANK', 'Kotak Mahindra Bank', 'KOTAKBANK.NS', 'stock'),
('LTIM', 'LTIMindtree', 'LTIM.NS', 'stock'),
('MARUTI', 'Maruti Suzuki', 'MARUTI.NS', 'stock'),
('NESTLEIND', 'Nestle India', 'NESTLEIND.NS', 'stock'),
('NTPC', 'NTPC', 'NTPC.NS', 'stock'),
('ONGC', 'ONGC', 'ONGC.NS', 'stock'),
('POWERGRID', 'Power Grid Corp', 'POWERGRID.NS', 'stock'),
('SBILIFE', 'SBI Life Insurance', 'SBILIFE.NS', 'stock'),
('SUNPHARMA', 'Sun Pharmaceutical', 'SUNPHARMA.NS', 'stock'),
('TATACONSUM', 'Tata Consumer', 'TATACONSUM.NS', 'stock'),
('TATAMOTORS', 'Tata Motors', 'TATAMOTORS.NS', 'stock'),
('TATASTEEL', 'Tata Steel', 'TATASTEEL.NS', 'stock'),
('TECHM', 'Tech Mahindra', 'TECHM.NS', 'stock'),
('TITAN', 'Titan Company', 'TITAN.NS', 'stock'),
('TRENT', 'Trent', 'TRENT.NS', 'stock'),
('ULTRACEMCO', 'UltraTech Cement', 'ULTRACEMCO.NS', 'stock'),
('ABB', 'ABB India', 'ABB.NS', 'stock'),
('ADANIGREEN', 'Adani Green Energy', 'ADANIGREEN.NS', 'stock'),
('ADANIPOWER', 'Adani Power', 'ADANIPOWER.NS', 'stock'),
('AMBUJACEM', 'Ambuja Cements', 'AMBUJACEM.NS', 'stock'),
('ATGL', 'Adani Total Gas', 'ATGL.NS', 'stock'),
('BANKBARODA', 'Bank of Baroda', 'BANKBARODA.NS', 'stock'),
('BOSCHLTD', 'Bosch', 'BOSCHLTD.NS', 'stock'),
('CANBK', 'Canara Bank', 'CANBK.NS', 'stock'),
('CHOLAFIN', 'Cholamandalam Inv', 'CHOLAFIN.NS', 'stock'),
('COLPAL', 'Colgate-Palmolive', 'COLPAL.NS', 'stock'),
('DLF', 'DLF', 'DLF.NS', 'stock'),
('DABUR', 'Dabur India', 'DABUR.NS', 'stock'),
('GODREJCP', 'Godrej Consumer', 'GODREJCP.NS', 'stock'),
('GAIL', 'GAIL India', 'GAIL.NS', 'stock'),
('HAL', 'Hindustan Aeronautics', 'HAL.NS', 'stock'),
('HAVELLS', 'Havells India', 'HAVELLS.NS', 'stock'),
('ICICIGI', 'ICICI Lombard GIC', 'ICICIGI.NS', 'stock'),
('IOC', 'Indian Oil Corp', 'IOC.NS', 'stock'),
('IRCTC', 'IRCTC', 'IRCTC.NS', 'stock'),
('IRFC', 'Indian Railway Finance', 'IRFC.NS', 'stock'),
('JINDALSTEL', 'Jindal Steel & Power', 'JINDALSTEL.NS', 'stock'),
('JIOFIN', 'Jio Financial', 'JIOFIN.NS', 'stock'),
('LICI', 'Life Insurance Corp', 'LICI.NS', 'stock'),
('MARICO', 'Marico', 'MARICO.NS', 'stock'),
('MOTHERSON', 'Motherson Sumi', 'MOTHERSON.NS', 'stock'),
('NHPC', 'NHPC', 'NHPC.NS', 'stock'),
('PIDILITIND', 'Pidilite Industries', 'PIDILITIND.NS', 'stock'),
('PFC', 'Power Finance Corp', 'PFC.NS', 'stock'),
('PNB', 'Punjab National Bank', 'PNB.NS', 'stock'),
('RECLTD', 'REC', 'RECLTD.NS', 'stock'),
('SHREECEM', 'Shree Cement', 'SHREECEM.NS', 'stock'),
('SHRIRAMFIN', 'Shriram Finance', 'SHRIRAMFIN.NS', 'stock'),
('SIEMENS', 'Siemens', 'SIEMENS.NS', 'stock'),
('TORNTPHARM', 'Torrent Pharma', 'TORNTPHARM.NS', 'stock'),
('TVSMOTOR', 'TVS Motor', 'TVSMOTOR.NS', 'stock'),
('UNIONBANK', 'Union Bank', 'UNIONBANK.NS', 'stock'),
('VEDL', 'Vedanta', 'VEDL.NS', 'stock'),
('VBL', 'Varun Beverages', 'VBL.NS', 'stock'),
('ZOMATO', 'Zomato', 'ZOMATO.NS', 'stock'),
('ZYDUSLIFE', 'Zydus Lifesciences', 'ZYDUSLIFE.NS', 'stock'),
('AARTIIND', 'Aarti Industries', 'AARTIIND.NS', 'stock'),
('ACC', 'ACC', 'ACC.NS', 'stock'),
('AIAENG', 'AIA Engineering', 'AIAENG.NS', 'stock'),
('ALKEM', 'Alkem Laboratories', 'ALKEM.NS', 'stock'),
('ALOKINDS', 'Alok Industries', 'ALOKINDS.NS', 'stock'),
('APLLTD', 'Alembic Pharma', 'APLLTD.NS', 'stock'),
('ASTRAL', 'Astral', 'ASTRAL.NS', 'stock'),
('AUROPHARMA', 'Aurobindo Pharma', 'AUROPHARMA.NS', 'stock'),
('BALKRISIND', 'Balkrishna Industries', 'BALKRISIND.NS', 'stock'),
('BANDHANBNK', 'Bandhan Bank', 'BANDHANBNK.NS', 'stock'),
('BATAINDIA', 'Bata India', 'BATAINDIA.NS', 'stock'),
('BERGEPAINT', 'Berger Paints', 'BERGEPAINT.NS', 'stock'),
('BHARATFORG', 'Bharat Forge', 'BHARATFORG.NS', 'stock'),
('BIOCON', 'Biocon', 'BIOCON.NS', 'stock'),
('CANFINHOME', 'Can Fin Homes', 'CANFINHOME.NS', 'stock'),
('CASTROLIND', 'Castrol India', 'CASTROLIND.NS', 'stock'),
('CENTRALBK', 'Central Bank', 'CENTRALBK.NS', 'stock'),
('CESC', 'CESC', 'CESC.NS', 'stock'),
('CGPOWER', 'CG Power', 'CGPOWER.NS', 'stock'),
('CHAMBLFERT', 'Chambal Fertilisers', 'CHAMBLFERT.NS', 'stock'),
('COFORGE', 'Coforge', 'COFORGE.NS', 'stock'),
('CONCOR', 'Container Corp', 'CONCOR.NS', 'stock'),
('CROMPTON', 'Crompton Greaves CE', 'CROMPTON.NS', 'stock'),
('CUB', 'City Union Bank', 'CUB.NS', 'stock'),
('CUMMINSIND', 'Cummins India', 'CUMMINSIND.NS', 'stock'),
('DALBHARAT', 'Dalmia Bharat', 'DALBHARAT.NS', 'stock'),
('DEEPAKFERT', 'Deepak Fertilisers', 'DEEPAKFERT.NS', 'stock'),
('DEEPAKNTR', 'Deepak Nitrite', 'DEEPAKNTR.NS', 'stock'),
('DELTACORP', 'Delta Corp', 'DELTACORP.NS', 'stock'),
('DEVYANI', 'Devyani International', 'DEVYANI.NS', 'stock'),
('DIXON', 'Dixon Technologies', 'DIXON.NS', 'stock'),
('ELGIEQUIP', 'Elgi Equipments', 'ELGIEQUIP.NS', 'stock'),
('EMAMILTD', 'Emami', 'EMAMILTD.NS', 'stock'),
('ENDURANCE', 'Endurance Technologies', 'ENDURANCE.NS', 'stock'),
('ESCORTS', 'Escorts Kubota', 'ESCORTS.NS', 'stock'),
('EXIDEIND', 'Exide Industries', 'EXIDEIND.NS', 'stock'),
('FEDERALBNK', 'Federal Bank', 'FEDERALBNK.NS', 'stock'),
('FORTIS', 'Fortis Healthcare', 'FORTIS.NS', 'stock'),
('GLENMARK', 'Glenmark Pharma', 'GLENMARK.NS', 'stock'),
('GMRAIRPORT', 'GMR Airports', 'GMRAIRPORT.NS', 'stock'),
('GNFC', 'GNFC', 'GNFC.NS', 'stock'),
('GODREJPROP', 'Godrej Properties', 'GODREJPROP.NS', 'stock'),
('GRANULES', 'Granules India', 'GRANULES.NS', 'stock'),
('GSPL', 'Gujarat State Petronet', 'GSPL.NS', 'stock'),
('GUJGASLTD', 'Gujarat Gas', 'GUJGASLTD.NS', 'stock'),
('HDFCAMC', 'HDFC AMC', 'HDFCAMC.NS', 'stock'),
('HINDCOPPER', 'Hindustan Copper', 'HINDCOPPER.NS', 'stock'),
('HINDPETRO', 'HPCL', 'HINDPETRO.NS', 'stock'),
('HONAUT', 'Honeywell Automation', 'HONAUT.NS', 'stock'),
('IDFCFIRSTB', 'IDFC First Bank', 'IDFCFIRSTB.NS', 'stock'),
('IEX', 'Indian Energy Exchange', 'IEX.NS', 'stock'),
('IIFL', 'IIFL Finance', 'IIFL.NS', 'stock'),
('INDHOTEL', 'Indian Hotels', 'INDHOTEL.NS', 'stock'),
('INDUSTOWER', 'Indus Towers', 'INDUSTOWER.NS', 'stock'),
('INTELLECT', 'Intellect Design Arena', 'INTELLECT.NS', 'stock'),
('IPCALAB', 'IPCA Laboratories', 'IPCALAB.NS', 'stock'),
('IREDA', 'IREDA', 'IREDA.NS', 'stock'),
('ISEC', 'ICICI Securities', 'ISEC.NS', 'stock'),
('JKCEMENT', 'JK Cement', 'JKCEMENT.NS', 'stock'),
('JSL', 'Jindal Stainless', 'JSL.NS', 'stock'),
('JUBLFOOD', 'Jubilant FoodWorks', 'JUBLFOOD.NS', 'stock'),
('KALYANKJIL', 'Kalyan Jewellers', 'KALYANKJIL.NS', 'stock'),
('KEI', 'KEI Industries', 'KEI.NS', 'stock'),
('KPITTECH', 'KPIT Technologies', 'KPITTECH.NS', 'stock'),
('LAURUSLABS', 'Laurus Labs', 'LAURUSLABS.NS', 'stock'),
('LICHSGFIN', 'LIC Housing Finance', 'LICHSGFIN.NS', 'stock'),
('LLOYDSME', 'Lloyds Metals', 'LLOYDSME.NS', 'stock'),
('LUPIN', 'Lupin', 'LUPIN.NS', 'stock'),
('MANAPPURAM', 'Manappuram Finance', 'MANAPPURAM.NS', 'stock'),
('MANKIND', 'Mankind Pharma', 'MANKIND.NS', 'stock'),
('MAXHEALTH', 'Max Healthcare', 'MAXHEALTH.NS', 'stock'),
('MCX', 'Multi Commodity Exchange', 'MCX.NS', 'stock'),
('METROPOLIS', 'Metropolis Healthcare', 'METROPOLIS.NS', 'stock'),
('MFSL', 'Max Financial Services', 'MFSL.NS', 'stock'),
('MGL', 'Mahanagar Gas', 'MGL.NS', 'stock'),
('MOTILALOFS', 'Motilal Oswal', 'MOTILALOFS.NS', 'stock'),
('MPHASIS', 'Mphasis', 'MPHASIS.NS', 'stock'),
('MUTHOOTFIN', 'Muthoot Finance', 'MUTHOOTFIN.NS', 'stock'),
('NATIONALUM', 'National Aluminium', 'NATIONALUM.NS', 'stock'),
('NAUKRI', 'Info Edge (Naukri)', 'NAUKRI.NS', 'stock'),
('NAVINFLUOR', 'Navin Fluorine', 'NAVINFLUOR.NS', 'stock'),
('NBCC', 'NBCC India', 'NBCC.NS', 'stock'),
('NCC', 'NCC', 'NCC.NS', 'stock'),
('NMDC', 'NMDC', 'NMDC.NS', 'stock'),
('OBEROIRLTY', 'Oberoi Realty', 'OBEROIRLTY.NS', 'stock'),
('OFSS', 'Oracle Financial', 'OFSS.NS', 'stock'),
('PAGEIND', 'Page Industries', 'PAGEIND.NS', 'stock'),
('PAYTM', 'One97 Communications', 'PAYTM.NS', 'stock'),
('PERSISTENT', 'Persistent Systems', 'PERSISTENT.NS', 'stock'),
('PETRONET', 'Petronet LNG', 'PETRONET.NS', 'stock'),
('PHOENIXLTD', 'Phoenix Mills', 'PHOENIXLTD.NS', 'stock'),
('PIIND', 'PI Industries', 'PIIND.NS', 'stock'),
('POLYCAB', 'Polycab India', 'POLYCAB.NS', 'stock'),
('POONAWALLA', 'Poonawalla Fincorp', 'POONAWALLA.NS', 'stock'),
('PRESTIGE', 'Prestige Estates', 'PRESTIGE.NS', 'stock'),
('PVRINOX', 'PVR Inox', 'PVRINOX.NS', 'stock'),
('RAJESHEXPO', 'Rajesh Exports', 'RAJESHEXPO.NS', 'stock'),
('RAMCOCEM', 'Ramco Cements', 'RAMCOCEM.NS', 'stock'),
('RBLBANK', 'RBL Bank', 'RBLBANK.NS', 'stock'),
('SAIL', 'Steel Authority', 'SAIL.NS', 'stock'),
('SBICARD', 'SBI Cards', 'SBICARD.NS', 'stock'),
('SJVN', 'SJVN', 'SJVN.NS', 'stock'),
('SONACOMS', 'Sona BLW Precision', 'SONACOMS.NS', 'stock'),
('SRF', 'SRF', 'SRF.NS', 'stock'),
('STARHEALTH', 'Star Health Insurance', 'STARHEALTH.NS', 'stock'),
('SUNDARMFIN', 'Sundaram Finance', 'SUNDARMFIN.NS', 'stock'),
('SUNDRMFAST', 'Sundram Fasteners', 'SUNDRMFAST.NS', 'stock'),
('SUPREMEIND', 'Supreme Industries', 'SUPREMEIND.NS', 'stock'),
('SYNGENE', 'Syngene International', 'SYNGENE.NS', 'stock'),
('TATACHEM', 'Tata Chemicals', 'TATACHEM.NS', 'stock'),
('TATACOMM', 'Tata Communications', 'TATACOMM.NS', 'stock'),
('TATAELXSI', 'Tata Elxsi', 'TATAELXSI.NS', 'stock'),
('TATAPOWER', 'Tata Power', 'TATAPOWER.NS', 'stock'),
('TIINDIA', 'Tube Investments', 'TIINDIA.NS', 'stock'),
('TORNTPOWER', 'Torrent Power', 'TORNTPOWER.NS', 'stock'),
('TTML', 'Tata Teleservices', 'TTML.NS', 'stock'),
('UBL', 'United Breweries', 'UBL.NS', 'stock'),
('UNOMINDA', 'UNO Minda', 'UNOMINDA.NS', 'stock'),
('UPL', 'UPL', 'UPL.NS', 'stock'),
('VOLTAS', 'Voltas', 'VOLTAS.NS', 'stock'),
('WHIRLPOOL', 'Whirlpool India', 'WHIRLPOOL.NS', 'stock'),
('YESBANK', 'Yes Bank', 'YESBANK.NS', 'stock'),
('3MINDIA', '3M India', '3MINDIA.NS', 'stock'),
('AAVAS', 'Aavas Financiers', 'AAVAS.NS', 'stock'),
('ABCAPITAL', 'Aditya Birla Capital', 'ABCAPITAL.NS', 'stock'),
('ABFRL', 'Aditya Birla Fashion', 'ABFRL.NS', 'stock'),
('ABSLAMC', 'ABSL AMC', 'ABSLAMC.NS', 'stock'),
('AEGISCHEM', 'Aegis Chemicals', 'AEGISCHEM.NS', 'stock'),
('AFFLE', 'Affle India', 'AFFLE.NS', 'stock'),
('AJANTPHARM', 'Ajanta Pharma', 'AJANTPHARM.NS', 'stock'),
('ALKYLAMINE', 'Alkyl Amines', 'ALKYLAMINE.NS', 'stock'),
('ALLCARGO', 'Allcargo Logistics', 'ALLCARGO.NS', 'stock'),
('AMARAJABAT', 'Amara Raja Energy', 'AMARAJABAT.NS', 'stock'),
('ANGELONE', 'Angel One', 'ANGELONE.NS', 'stock'),
('APARINDS', 'Apar Industries', 'APARINDS.NS', 'stock'),
('APTUS', 'Aptus Value Housing', 'APTUS.NS', 'stock'),
('ASHOKLEY', 'Ashok Leyland', 'ASHOKLEY.NS', 'stock'),
('ATUL', 'Atul', 'ATUL.NS', 'stock'),
('AVANTEL', 'Avantel', 'AVANTEL.NS', 'stock'),
('AVANTIFEED', 'Avanti Feeds', 'AVANTIFEED.NS', 'stock'),
('BAJAJHLDNG', 'Bajaj Holdings', 'BAJAJHLDNG.NS', 'stock'),
('BALAMINES', 'Balaji Amines', 'BALAMINES.NS', 'stock'),
('BASF', 'BASF India', 'BASF.NS', 'stock'),
('BAYERCROP', 'Bayer CropScience', 'BAYERCROP.NS', 'stock'),
('BDL', 'Bharat Dynamics', 'BDL.NS', 'stock'),
('BHARATRAS', 'Bharat Rasayan', 'BHARATRAS.NS', 'stock'),
('BHEL', 'BHEL', 'BHEL.NS', 'stock'),
('BIRLACORPN', 'Birla Corporation', 'BIRLACORPN.NS', 'stock'),
('BLUESTARCO', 'Blue Star', 'BLUESTARCO.NS', 'stock'),
('BSOFT', 'Birlasoft', 'BSOFT.NS', 'stock'),
('BSE', 'BSE', 'BSE.NS', 'stock'),
('CAMPUS', 'Campus Activewear', 'CAMPUS.NS', 'stock'),
('CARBORUNIV', 'Carborundum Universal', 'CARBORUNIV.NS', 'stock'),
('CDSL', 'CDSL', 'CDSL.NS', 'stock'),
('CENTURYPLY', 'Century Plyboards', 'CENTURYPLY.NS', 'stock'),
('CERA', 'Cera Sanitaryware', 'CERA.NS', 'stock'),
('CHALET', 'Chalet Hotels', 'CHALET.NS', 'stock'),
('CLEAN', 'Clean Science', 'CLEAN.NS', 'stock'),
('COCHINSHIP', 'Cochin Shipyard', 'COCHINSHIP.NS', 'stock'),
('CRISIL', 'CRISIL', 'CRISIL.NS', 'stock'),
('CYIENT', 'Cyient', 'CYIENT.NS', 'stock'),
('DATAPATTNS', 'Data Patterns', 'DATAPATTNS.NS', 'stock'),
('DCMSHRIRAM', 'DCM Shriram', 'DCMSHRIRAM.NS', 'stock'),
('DMART', 'Avenue Supermarts', 'DMART.NS', 'stock'),
('ECLERX', 'eClerx Services', 'ECLERX.NS', 'stock'),
('EIDPARRY', 'EID Parry', 'EIDPARRY.NS', 'stock'),
('ELECON', 'Elecon Engineering', 'ELECON.NS', 'stock'),
('EPIGRAL', 'Epigral', 'EPIGRAL.NS', 'stock'),
('EQUITASBNK', 'Equitas Small Fin Bank', 'EQUITASBNK.NS', 'stock'),
('FACT', 'Fertilizers & Chemicals', 'FACT.NS', 'stock'),
('FINEORG', 'Fine Organic', 'FINEORG.NS', 'stock'),
('FIVESTAR', 'Five-Star Business', 'FIVESTAR.NS', 'stock'),
('GARFIBRES', 'Garware Technical', 'GARFIBRES.NS', 'stock'),
('GILLETTE', 'Gillette India', 'GILLETTE.NS', 'stock'),
('GLAXO', 'GSK Pharma', 'GLAXO.NS', 'stock'),
('GMMPFAUDLR', 'GMM Pfaudler', 'GMMPFAUDLR.NS', 'stock'),
('GODFRYPHLP', 'Godfrey Phillips', 'GODFRYPHLP.NS', 'stock'),
('GPPL', 'Gujarat Pipavav Port', 'GPPL.NS', 'stock'),
('GRINDWELL', 'Grindwell Norton', 'GRINDWELL.NS', 'stock'),
('GRSE', 'Garden Reach Shipbuilders', 'GRSE.NS', 'stock'),
('HAPPSTMNDS', 'Happiest Minds', 'HAPPSTMNDS.NS', 'stock'),
('HBLPOWER', 'HBL Power Systems', 'HBLPOWER.NS', 'stock'),
('HEG', 'HEG', 'HEG.NS', 'stock'),
('HINDZINC', 'Hindustan Zinc', 'HINDZINC.NS', 'stock'),
('HOMEFIRST', 'Home First Finance', 'HOMEFIRST.NS', 'stock'),
('HUDCO', 'HUDCO', 'HUDCO.NS', 'stock'),
('IDBI', 'IDBI Bank', 'IDBI.NS', 'stock'),
('IDEA', 'Vodafone Idea', 'IDEA.NS', 'stock'),
('IIFLWAM', '360 ONE WAM', 'IIFLWAM.NS', 'stock'),
('INDIAMART', 'IndiaMART', 'INDIAMART.NS', 'stock'),
('INDIANB', 'Indian Bank', 'INDIANB.NS', 'stock'),
('INDIGO', 'IndiGo Airlines', 'INDIGO.NS', 'stock'),
('JBCHEPHARM', 'JB Chemicals', 'JBCHEPHARM.NS', 'stock'),
('JKLAKSHMI', 'JK Lakshmi Cement', 'JKLAKSHMI.NS', 'stock'),
('JKPAPER', 'JK Paper', 'JKPAPER.NS', 'stock'),
('JMFINANCIL', 'JM Financial', 'JMFINANCIL.NS', 'stock'),
('JSWENERGY', 'JSW Energy', 'JSWENERGY.NS', 'stock'),
('JTEKTINDIA', 'JTEKT India', 'JTEKTINDIA.NS', 'stock'),
('JUSTDIAL', 'Just Dial', 'JUSTDIAL.NS', 'stock'),
('KALPATPOWR', 'Kalpataru Projects', 'KALPATPOWR.NS', 'stock'),
('KARURVYSYA', 'Karur Vysya Bank', 'KARURVYSYA.NS', 'stock'),
('KEC', 'KEC International', 'KEC.NS', 'stock'),
('KFINTECH', 'KFin Technologies', 'KFINTECH.NS', 'stock'),
('KIOCL', 'KIOCL', 'KIOCL.NS', 'stock'),
('KNRCON', 'KNR Constructions', 'KNRCON.NS', 'stock'),
('KPRMILL', 'KPR Mill', 'KPRMILL.NS', 'stock'),
('KRBL', 'KRBL', 'KRBL.NS', 'stock'),
('KSB', 'KSB', 'KSB.NS', 'stock'),
('LATENTVIEW', 'Latent View Analytics', 'LATENTVIEW.NS', 'stock'),
('LAXMIMACH', 'Lakshmi Machine Works', 'LAXMIMACH.NS', 'stock'),
('LINDEINDIA', 'Linde India', 'LINDEINDIA.NS', 'stock'),
('LTTS', 'L&T Technology', 'LTTS.NS', 'stock'),
('LUXIND', 'Lux Industries', 'LUXIND.NS', 'stock'),
('MAHABANK', 'Bank of Maharashtra', 'MAHABANK.NS', 'stock'),
('MAHLIFE', 'Mahindra Lifespace', 'MAHLIFE.NS', 'stock'),
('MAHSEAMLES', 'Maharashtra Seamless', 'MAHSEAMLES.NS', 'stock'),
('MASTEK', 'Mastek', 'MASTEK.NS', 'stock'),
('MEDANTA', 'Medanta (GCPL)', 'MEDANTA.NS', 'stock'),
('MEDPLUS', 'MedPlus Health', 'MEDPLUS.NS', 'stock'),
('METROBRAND', 'Metro Brands', 'METROBRAND.NS', 'stock'),
('MHRIL', 'Mahindra Holidays', 'MHRIL.NS', 'stock'),
('MIDHANI', 'Mishra Dhatu Nigam', 'MIDHANI.NS', 'stock'),
('MMTC', 'MMTC', 'MMTC.NS', 'stock'),
('MOIL', 'MOIL', 'MOIL.NS', 'stock'),
('MRPL', 'MRPL', 'MRPL.NS', 'stock'),
('MSUMI', 'Motherson Sumi Wiring', 'MSUMI.NS', 'stock'),
('MUTHOOTMF', 'Muthoot Microfin', 'MUTHOOTMF.NS', 'stock'),
('NATCOPHARM', 'Natco Pharma', 'NATCOPHARM.NS', 'stock'),
('NIACL', 'New India Assurance', 'NIACL.NS', 'stock'),
('NLCINDIA', 'NLC India', 'NLCINDIA.NS', 'stock'),
('NUVAMA', 'Nuvama Wealth', 'NUVAMA.NS', 'stock'),
('NYKAA', 'Nykaa (FSN E-Commerce)', 'NYKAA.NS', 'stock'),
('OLECTRA', 'Olectra Greentech', 'OLECTRA.NS', 'stock'),
('ORIENTELEC', 'Orient Electric', 'ORIENTELEC.NS', 'stock'),
('PGHH', 'P&G Hygiene', 'PGHH.NS', 'stock'),
('PGHL', 'Procter & Gamble Health', 'PGHL.NS', 'stock'),
('POLICYBZR', 'PB Fintech', 'POLICYBZR.NS', 'stock'),
('POLYMED', 'Poly Medicure', 'POLYMED.NS', 'stock'),
('POWERINDIA', 'Hitachi Energy India', 'POWERINDIA.NS', 'stock'),
('PPLPHARMA', 'Piramal Pharma', 'PPLPHARMA.NS', 'stock'),
('PRSMJOHNSN', 'Prism Johnson', 'PRSMJOHNSN.NS', 'stock'),
('QUESS', 'Quess Corp', 'QUESS.NS', 'stock'),
('RADICO', 'Radico Khaitan', 'RADICO.NS', 'stock'),
('RAIN', 'Rain Industries', 'RAIN.NS', 'stock'),
('RALLIS', 'Rallis India', 'RALLIS.NS', 'stock'),
('RATNAMANI', 'Ratnamani Metals', 'RATNAMANI.NS', 'stock'),
('RAYMOND', 'Raymond', 'RAYMOND.NS', 'stock'),
('REDINGTON', 'Redington', 'REDINGTON.NS', 'stock'),
('RELAXO', 'Relaxo Footwears', 'RELAXO.NS', 'stock'),
('RITES', 'RITES', 'RITES.NS', 'stock'),
('ROSSARI', 'Rossari Biotech', 'ROSSARI.NS', 'stock'),
('ROUTE', 'Route Mobile', 'ROUTE.NS', 'stock'),
('RVNL', 'RVNL', 'RVNL.NS', 'stock'),
('SAPPHIRE', 'Sapphire Foods', 'SAPPHIRE.NS', 'stock'),
('SCHAEFFLER', 'Schaeffler India', 'SCHAEFFLER.NS', 'stock'),
('SOLARINDS', 'Solar Industries', 'SOLARINDS.NS', 'stock'),
('SOLARA', 'Solara Active Pharma', 'SOLARA.NS', 'stock'),
('SOUTHBANK', 'South Indian Bank', 'SOUTHBANK.NS', 'stock'),
('SPARC', 'Sun Pharma Advanced', 'SPARC.NS', 'stock'),
('STAR', 'Strides Pharma', 'STAR.NS', 'stock'),
('STARCEMENT', 'Star Cement', 'STARCEMENT.NS', 'stock'),
('SUDARSCHEM', 'Sudarshan Chemical', 'SUDARSCHEM.NS', 'stock'),
('SUMICHEM', 'Sumitomo Chemical', 'SUMICHEM.NS', 'stock'),
('SUNTV', 'Sun TV Network', 'SUNTV.NS', 'stock'),
('SUPRAJIT', 'Suprajit Engineering', 'SUPRAJIT.NS', 'stock'),
('SUVENPHAR', 'Suven Pharma', 'SUVENPHAR.NS', 'stock'),
('SWSOLAR', 'Sterling & Wilson Solar', 'SWSOLAR.NS', 'stock'),
('SYMPHONY', 'Symphony', 'SYMPHONY.NS', 'stock'),
('TANLA', 'Tanla Platforms', 'TANLA.NS', 'stock'),
('TATAINVEST', 'Tata Investment', 'TATAINVEST.NS', 'stock'),
('TCIEXP', 'TCI Express', 'TCIEXP.NS', 'stock'),
('THERMAX', 'Thermax', 'THERMAX.NS', 'stock'),
('TIMKEN', 'Timken India', 'TIMKEN.NS', 'stock'),
('TRITURBINE', 'Triveni Turbine', 'TRITURBINE.NS', 'stock'),
('TRIDENT', 'Trident', 'TRIDENT.NS', 'stock'),
('TRIVENI', 'Triveni Engineering', 'TRIVENI.NS', 'stock'),
('UCOBANK', 'UCO Bank', 'UCOBANK.NS', 'stock'),
('UJJIVANSFB', 'Ujjivan Small Finance', 'UJJIVANSFB.NS', 'stock'),
('UTIAMC', 'UTI AMC', 'UTIAMC.NS', 'stock'),
('VGUARD', 'V-Guard Industries', 'VGUARD.NS', 'stock'),
('VIJAYA', 'Vijaya Diagnostic', 'VIJAYA.NS', 'stock'),
('VINATIORGA', 'Vinati Organics', 'VINATIORGA.NS', 'stock'),
('WELCORP', 'Welspun Corp', 'WELCORP.NS', 'stock'),
('WELSPUNIND', 'Welspun Living', 'WELSPUNIND.NS', 'stock'),
('WESTLIFE', 'Westlife Foodworld', 'WESTLIFE.NS', 'stock'),
('ZEEL', 'Zee Entertainment', 'ZEEL.NS', 'stock'),
('ZENSAR', 'Zensar Technologies', 'ZENSAR.NS', 'stock'),
('AADHARHFC', 'Aadhar Housing', 'AADHARHFC.NS', 'stock'),
('ACCELYA', 'Accelya Solutions', 'ACCELYA.NS', 'stock'),
('ACE', 'Action Construction', 'ACE.NS', 'stock'),
('ADVENZYMES', 'Advanced Enzyme', 'ADVENZYMES.NS', 'stock'),
('AETHER', 'Aether Industries', 'AETHER.NS', 'stock'),
('ANANTRAJ', 'Anant Raj', 'ANANTRAJ.NS', 'stock'),
('ANDHRAPET', 'Andhra Petrochemicals', 'ANDHRAPET.NS', 'stock'),
('ANURAS', 'Anupam Rasayan', 'ANURAS.NS', 'stock'),
('APOLLOTYRE', 'Apollo Tyres', 'APOLLOTYRE.NS', 'stock'),
('ASAHIINDIA', 'Asahi India Glass', 'ASAHIINDIA.NS', 'stock'),
('ASTERDM', 'Aster DM Healthcare', 'ASTERDM.NS', 'stock'),
('BANARISUG', 'Bannari Amman Sugars', 'BANARISUG.NS', 'stock'),
('BEML', 'BEML', 'BEML.NS', 'stock'),
('BLS', 'BLS International', 'BLS.NS', 'stock'),
('BRIGADE', 'Brigade Enterprises', 'BRIGADE.NS', 'stock'),
('CAMLINFINE', 'Camlin Fine Sciences', 'CAMLINFINE.NS', 'stock'),
('CAPLIPOINT', 'Caplin Point Labs', 'CAPLIPOINT.NS', 'stock'),
('CARYSIL', 'Carysil', 'CARYSIL.NS', 'stock'),
('CEATLTD', 'CEAT', 'CEATLTD.NS', 'stock'),
('CENTURYTEX', 'Century Textiles', 'CENTURYTEX.NS', 'stock'),
('CHEMCON', 'Chemcon Speciality', 'CHEMCON.NS', 'stock'),
('CHENNPETRO', 'Chennai Petroleum', 'CHENNPETRO.NS', 'stock'),
('CHEMPLASTS', 'Chemplast Sanmar', 'CHEMPLASTS.NS', 'stock'),
('CIEINDIA', 'CIE Automotive', 'CIEINDIA.NS', 'stock'),
('COROMANDEL', 'Coromandel International', 'COROMANDEL.NS', 'stock'),
('CRAFTSMAN', 'Craftsman Automation', 'CRAFTSMAN.NS', 'stock'),
('CREDITACC', 'CreditAccess Grameen', 'CREDITACC.NS', 'stock'),
('CSBBANK', 'CSB Bank', 'CSBBANK.NS', 'stock'),
('DCBBANK', 'DCB Bank', 'DCBBANK.NS', 'stock'),
('DHANUKA', 'Dhanuka Agritech', 'DHANUKA.NS', 'stock'),
('DOLLARSIND', 'Dollar Industries', 'DOLLARSIND.NS', 'stock'),
('DWARKESH', 'Dwarikesh Sugar', 'DWARKESH.NS', 'stock'),
('DYNAMATECH', 'Dynamatic Technologies', 'DYNAMATECH.NS', 'stock'),
('EASEMYTRIP', 'Easy Trip Planners', 'EASEMYTRIP.NS', 'stock'),
('EDELWEISS', 'Edelweiss Financial', 'EDELWEISS.NS', 'stock'),
('EIHOTEL', 'EIH (Oberoi Hotels)', 'EIHOTEL.NS', 'stock'),
('EMD', 'eMudhra', 'EMD.NS', 'stock'),
('ENGINERSIN', 'Engineers India', 'ENGINERSIN.NS', 'stock'),
('ERIS', 'Eris Lifesciences', 'ERIS.NS', 'stock'),
('ETHOSLTD', 'Ethos', 'ETHOSLTD.NS', 'stock'),
('EVERESTIND', 'Everest Industries', 'EVERESTIND.NS', 'stock'),
('FCL', 'Fineotex Chemical', 'FCL.NS', 'stock'),
('FDC', 'FDC', 'FDC.NS', 'stock'),
('FIEMIND', 'Fiem Industries', 'FIEMIND.NS', 'stock'),
('FINPIPE', 'Finolex Industries', 'FINPIPE.NS', 'stock'),
('FLUOROCHEM', 'Gujarat Fluorochemicals', 'FLUOROCHEM.NS', 'stock'),
('GE', 'GE T&D India', 'GE.NS', 'stock'),
('GENUSPOWER', 'Genus Power', 'GENUSPOWER.NS', 'stock'),
('GHCL', 'GHCL', 'GHCL.NS', 'stock'),
('GICRE', 'GIC Re', 'GICRE.NS', 'stock'),
('GLAND', 'Gland Pharma', 'GLAND.NS', 'stock'),
('GLOBUSSPR', 'Globus Spirits', 'GLOBUSSPR.NS', 'stock'),
('GLS', 'Glenmark Life Sciences', 'GLS.NS', 'stock'),
('GOCOLORS', 'Go Fashion', 'GOCOLORS.NS', 'stock'),
('GODREJIND', 'Godrej Industries', 'GODREJIND.NS', 'stock'),
('GRAPHITE', 'Graphite India', 'GRAPHITE.NS', 'stock'),
('GREENPLY', 'Greenply Industries', 'GREENPLY.NS', 'stock'),
('GREENPANEL', 'Green Panel', 'GREENPANEL.NS', 'stock'),
('GRINFRA', 'GR Infraprojects', 'GRINFRA.NS', 'stock'),
('GSHIP', 'Great Eastern Shipping', 'GSHIP.NS', 'stock'),
('GUFICBIO', 'Gufic Biosciences', 'GUFICBIO.NS', 'stock'),
('HATHWAY', 'Hathway Cable', 'HATHWAY.NS', 'stock'),
('HERITGFOOD', 'Heritage Foods', 'HERITGFOOD.NS', 'stock'),
('HIKAL', 'Hikal', 'HIKAL.NS', 'stock'),
('HGS', 'Hinduja Global', 'HGS.NS', 'stock'),
('HINDWAREAP', 'Hindware Home', 'HINDWAREAP.NS', 'stock'),
('HSCL', 'Himadri Speciality', 'HSCL.NS', 'stock'),
('IBREALEST', 'Indiabulls Real Estate', 'IBREALEST.NS', 'stock'),
('ICRA', 'ICRA', 'ICRA.NS', 'stock'),
('IFBIND', 'IFB Industries', 'IFBIND.NS', 'stock'),
('IGPL', 'India Glycols', 'IGPL.NS', 'stock'),
('INDIGOPNTS', 'Indigo Paints', 'INDIGOPNTS.NS', 'stock'),
('IRB', 'IRB Infrastructure', 'IRB.NS', 'stock'),
('JAMNAAUTO', 'Jamna Auto', 'JAMNAAUTO.NS', 'stock'),
('JKTYRE', 'JK Tyre', 'JKTYRE.NS', 'stock'),
('JPPOWER', 'Jaiprakash Power', 'JPPOWER.NS', 'stock'),
('JTLIND', 'JTL Industries', 'JTLIND.NS', 'stock'),
('JUNIPER', 'Juniper Hotels', 'JUNIPER.NS', 'stock'),
('JYOTHYLAB', 'Jyothy Labs', 'JYOTHYLAB.NS', 'stock'),
('KAYNES', 'Kaynes Technology', 'KAYNES.NS', 'stock'),
('KIMS', 'Krishna Inst Medical', 'KIMS.NS', 'stock'),
('KOLTEPATIL', 'Kolte-Patil Developers', 'KOLTEPATIL.NS', 'stock'),
('KOPRAN', 'Kopran', 'KOPRAN.NS', 'stock'),
('LALPATHLAB', 'Dr Lal PathLabs', 'LALPATHLAB.NS', 'stock'),
('LEMONTREE', 'Lemon Tree Hotels', 'LEMONTREE.NS', 'stock'),
('MAPMYINDIA', 'CE Info Systems', 'MAPMYINDIA.NS', 'stock'),
('MAZAGON', 'Mazagon Dock', 'MAZAGON.NS', 'stock'),
('MRF', 'MRF', 'MRF.NS', 'stock'),
('NETWORK18', 'Network18 Media', 'NETWORK18.NS', 'stock'),
('NH', 'Narayana Hrudayalaya', 'NH.NS', 'stock'),
('NOCIL', 'NOCIL', 'NOCIL.NS', 'stock'),
('NOVARTIND', 'Novartis India', 'NOVARTIND.NS', 'stock'),
('NURECA', 'Nureca', 'NURECA.NS', 'stock'),
('PATANJALI', 'Patanjali Foods', 'PATANJALI.NS', 'stock'),
('PCBL', 'PCBL Chemical', 'PCBL.NS', 'stock'),
('PDSL', 'PDS', 'PDSL.NS', 'stock'),
('PENIND', 'Pennar Industries', 'PENIND.NS', 'stock'),
('PFIZER', 'Pfizer', 'PFIZER.NS', 'stock'),
('PNBHOUSING', 'PNB Housing Finance', 'PNBHOUSING.NS', 'stock'),
('PRINCEPIPE', 'Prince Pipes', 'PRINCEPIPE.NS', 'stock'),
('PRIVISCL', 'Privi Speciality', 'PRIVISCL.NS', 'stock'),
('RAINBOW', 'Rainbow Children''s', 'RAINBOW.NS', 'stock'),
('RAJRATAN', 'Rajratan Global Wire', 'RAJRATAN.NS', 'stock'),
('RENUKA', 'Shree Renuka Sugars', 'RENUKA.NS', 'stock'),
('ROSSELLIND', 'Rossell India', 'ROSSELLIND.NS', 'stock'),
('RPOWER', 'Reliance Power', 'RPOWER.NS', 'stock'),
('SANOFI', 'Sanofi India', 'SANOFI.NS', 'stock'),
('SAREGAMA', 'Saregama India', 'SAREGAMA.NS', 'stock'),
('SCHNEIDER', 'Schneider Electric', 'SCHNEIDER.NS', 'stock'),
('SFL', 'Sheela Foam', 'SFL.NS', 'stock'),
('SHILPAMED', 'Shilpa Medicare', 'SHILPAMED.NS', 'stock'),
('SHOPERSTOP', 'Shoppers Stop', 'SHOPERSTOP.NS', 'stock'),
('SOBHA', 'Sobha', 'SOBHA.NS', 'stock'),
('SWANENERGY', 'Swan Energy', 'SWANENERGY.NS', 'stock'),
('TARSONS', 'Tarsons Products', 'TARSONS.NS', 'stock'),
('TATAMETALI', 'Tata Metaliks', 'TATAMETALI.NS', 'stock'),
('TEAMLEASE', 'TeamLease Services', 'TEAMLEASE.NS', 'stock'),
('TEGA', 'Tega Industries', 'TEGA.NS', 'stock'),
('THYROCARE', 'Thyrocare Technologies', 'THYROCARE.NS', 'stock'),
('TINPLATE', 'Tinplate Company', 'TINPLATE.NS', 'stock'),
('TMB', 'Tamilnad Mercantile', 'TMB.NS', 'stock'),
('TVSHLTD', 'TVS Holdings', 'TVSHLTD.NS', 'stock'),
('VAIBHAVGBL', 'Vaibhav Global', 'VAIBHAVGBL.NS', 'stock'),
('VAKRANGEE', 'Vakrangee', 'VAKRANGEE.NS', 'stock'),
('VSTIND', 'VST Industries', 'VSTIND.NS', 'stock'),
('WABAG', 'VA Tech Wabag', 'WABAG.NS', 'stock'),
('WELENT', 'Welspun Enterprises', 'WELENT.NS', 'stock'),
('YATHARTH', 'Yatharth Hospital', 'YATHARTH.NS', 'stock'),
('ZFCVINDIA', 'ZF Commercial', 'ZFCVINDIA.NS', 'stock'),
('ZYDUSWELL', 'Zydus Wellness', 'ZYDUSWELL.NS', 'stock'),
('M_M', 'Mahindra & Mahindra', 'M%26M.NS', 'stock'),
('M_MFIN', 'Mahindra Finance', 'M%26MFIN.NS', 'stock'),
('L_TFH', 'L&T Finance', 'L%26TFH.NS', 'stock'),
('NAM_INDIA', 'Nippon Life India AMC', 'NAM-INDIA.NS', 'stock')
ON CONFLICT (symbol) DO NOTHING;